### ISSUE TITLE
恕我没看源码, 不支持双重for循环, 对吗?

### ISSUE THREAD

**Issue by zhangrunhao** [shalldie/mini-tpl#1]
`<div>
  <% for(var i = 0; i < data.length; i++){ %>
    <div class="row">
      <% for(var j = 0; j<i.length;j++){%>
        <div class="col">111</div>
      <%} %>
    </div>
  <% } %>
</div>`

只能渲染出来第一层.

**Comment by shalldie** [comment]
不好意思周末出去浪了，才看到。
你这个 `j<i.length` 是什么意思呢，，， i 是 `number` 类型啊，，，

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/37589078-1777b458-2b9f-11e8-9226-22ca844d5be1.png)

应该没问题，你再试试 ～

**Comment by zhangrunhao** [comment]
我曹, 大佬, 我的锅...  感恩  感恩.

**Comment by zhangrunhao** [comment]
给大佬添麻烦了..  此刻内心充满愧疚.
