### ISSUE TITLE
如果我data传输的是JSON数据可以获取吗？

### ISSUE THREAD

**Issue by ruanhanqin** [shalldie/mini-tpl#2]
如果我data传输的是JSON数据可啊以获取吗？ 好像如果data是JSON数据就无法读取，现在JSON用的比较多呀，看能否支持JSON数据

**Comment by shalldie** [comment]
你传的啥，那么模板里面的data就是啥。
可以是js对象，数组，字符串，balabala任何一种

**Comment by ruanhanqin** [comment]
var data = [{ "name": "tom", "age": "12" }, { "name": "lily", "age": "24" }, { "name": "lucy”, “age”: “55” }];

我传这个无法显示吧

**Comment by shalldie** [comment]
![image](https://user-images.githubusercontent.com/9987486/41642309-84924352-749a-11e8-8f32-544f4edd3d30.png)


没问题的。

把你的模板跟用法发一下吧，也许哪里有问题

**Comment by ruanhanqin** [comment]
可以了，谢谢

**Comment by ruanhanqin** [comment]
我的data如果想设计成从服务器获取的话要怎么做呢？

**Comment by shalldie** [comment]
```js
/**
 * 更新某块内容
 *
 * @param {any} data 数据
 */
function updateSome(data) {
    // 模板，这里是从页面的 <script id="tplContent" type="text/html"> 里面取，
    // 见 https://github.com/shalldie/mini-tpl#example
    // 或者你也可以放其它地方
    var content = document.getElementById('tplContent').innerHTML;
    // 把生成的string填充到页面
    $('xxx').html(miniTpl(content, data));
}

$.getJSON('xxx', function (result) {
    updateSome(result);
});
```

**Comment by ruanhanqin** [comment]
我研究下，

**Comment by ruanhanqin** [comment]
有没有相应的QQ群组呢？

**Comment by shalldie** [comment]
... 没有。

本身只是一个简单的模板引擎，负责 `模板+数据=》html` 这一步。
什么时候做，数据来源等随意组合。

**Comment by ruanhanqin** [comment]
我把它改成table形式，做数据展示

**Comment by ruanhanqin** [comment]
js跟html能分离吗？

**Comment by shalldie** [comment]
😂😂  当然可以啊。
